USE T_HRoads;

--DQL
--SELEÇÃO

SELECT * FROM TIPO ORDER BY IDTIPO ASC;
SELECT * FROM HABILIDADE ORDER BY IDHABILIDADE ASC;
SELECT * FROM CLASSE ORDER BY IDCLASSE ASC;
SELECT * FROM CLASSEHABILIDADE ORDER BY IDHABILIDADE ASC;
SELECT * FROM PERSONAGEM ORDER BY IDPERSONAGEM ASC;

--CONTAGEM DA HABILIDADE

SELECT COUNT(HABILIDADE) as CONTAGEM FROM HABILIDADE; 

SELECT H.IDHABILIDADE 
FROM HABILIDADE AS H ORDER BY IDHABILIDADE ASC;

SELECT T.TIPO
FROM TIPO T; 

SELECT H.HABILIDADE, H.IDTIPO
FROM HABILIDADE H;

SELECT P.NOME, P.IDCLASSE
FROM PERSONAGEM P;

SELECT P.NOME, C.CLASSE
FROM PERSONAGEM P
FULL JOIN CLASSE C
ON P.IDCLASSE = C.IDCLASSE;

SELECT H.HABILIDADE, C.CLASSE
FROM HABILIDADE H, CLASSE C;

SELECT H.*, C.*
FROM HABILIDADE H, CLASSE C;



