USE T_HRoads;

--DDL
--CRIACAO

CREATE TABLE TIPO
(
IDTIPO INT PRIMARY KEY IDENTITY
, TIPO VARCHAR (200) NOT NULL UNIQUE
);

CREATE TABLE HABILIDADE
(
IDHABILIDADE INT PRIMARY KEY IDENTITY
, HABILIDADE VARCHAR (200) NOT NULL
,IDTIPO INT FOREIGN KEY REFERENCES TIPO (IDTIPO)
);

CREATE TABLE CLASSE
(
IDCLASSE INT PRIMARY KEY IDENTITY
,CLASSE VARCHAR (200) NOT NULL UNIQUE
);

--TABELA INTERMEDIARIA

CREATE TABLE CLASSEHABILIDADE
(
IDCLASSE INT FOREIGN KEY REFERENCES CLASSE (IDCLASSE)
,IDHABILIDADE INT FOREIGN KEY REFERENCES HABILIDADE (IDHABILIDADE)
);

--FIM

CREATE TABLE PERSONAGEM
(
IDPERSONAGEM INT PRIMARY KEY IDENTITY
,NOME VARCHAR (200) NOT NULL UNIQUE
,IDCLASSE INT FOREIGN KEY REFERENCES CLASSE (IDCLASSE)
,CAPACIDADEVIDA INT 
,CAPACIDADEMANA INT
,DATAATT DATE
,DATACRIACAO DATE
);






